version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/lts-booking
      - ./build-11-07-2020:/lts-booking-build
    environment:
      - MONGO_URL=mongodb://mongo:27017/lts-booking
      - LTS_BOOKING_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
    working_dir: /lts-booking
    command: bash
    tty: true
    stdin_open: true

  mongo-seed:
    build: ./mock-data
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.17
    expose:
      - "27017"